// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Dashboard struct {
	EventCount      int        `json:"eventCount"`
	LastCollectedAt *time.Time `json:"lastCollectedAt,omitempty"`
	Mode            string     `json:"mode"`
	Stale           bool       `json:"stale"`
}

type Query struct {
}

type Vehicle struct {
	VehicleID    string    `json:"vehicleId"`
	RouteID      *string   `json:"routeId,omitempty"`
	TripID       *string   `json:"tripId,omitempty"`
	Latitude     float64   `json:"latitude"`
	Longitude    float64   `json:"longitude"`
	RecordedAt   time.Time `json:"recordedAt"`
	DelaySeconds *int      `json:"delaySeconds,omitempty"`
}
