package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"time"

	"ponctuel/services/api/graph/model"
)

// Dashboard is the resolver for the dashboard field.
func (r *queryResolver) Dashboard(ctx context.Context) (*model.Dashboard, error) {
	if r.repository == nil {
		return nil, fmt.Errorf("dashboard data unavailable")
	}
	eventCount, err := r.repository.CountEvents(ctx)
	if err != nil {
		return nil, fmt.Errorf("dashboard data unavailable")
	}
	var lastCollectedAt *time.Time
	if reader, ok := r.repository.(snapshotReader); ok {
		latest, err := reader.LatestSnapshotAt(ctx)
		if err != nil {
			return nil, fmt.Errorf("dashboard data unavailable")
		}
		if !latest.IsZero() {
			latest = latest.UTC()
			lastCollectedAt = &latest
		}
	}
	stale := lastCollectedAt == nil || time.Since(*lastCollectedAt) > r.freshnessWindow
	return &model.Dashboard{
		EventCount:      int(eventCount),
		LastCollectedAt: lastCollectedAt,
		Mode:            r.mode,
		Stale:           stale,
	}, nil
}

// Vehicles is the resolver for the vehicles field.
func (r *queryResolver) Vehicles(ctx context.Context, limit *int) ([]*model.Vehicle, error) {
	if r.repository == nil {
		return nil, fmt.Errorf("vehicle data unavailable")
	}
	requestedLimit := 500
	if limit != nil {
		requestedLimit = *limit
	}
	if requestedLimit < 0 {
		return nil, fmt.Errorf("vehicle limit must not be negative")
	}
	if requestedLimit > 500 {
		requestedLimit = 500
	}
	vehicles, err := r.repository.LatestVehicles(ctx)
	if err != nil {
		return nil, fmt.Errorf("vehicle data unavailable")
	}
	if len(vehicles) > requestedLimit {
		vehicles = vehicles[:requestedLimit]
	}
	result := make([]*model.Vehicle, 0, len(vehicles))
	for _, vehicle := range vehicles {
		result = append(result, &model.Vehicle{
			VehicleID:    vehicle.VehicleID,
			RouteID:      optionalString(vehicle.RouteID),
			TripID:       optionalString(vehicle.TripID),
			Latitude:     vehicle.Latitude,
			Longitude:    vehicle.Longitude,
			RecordedAt:   vehicle.RecordedAt.UTC(),
			DelaySeconds: optionalInt(vehicle.HasDelay, vehicle.DelaySeconds),
		})
	}
	return result, nil
}

func optionalString(value string) *string {
	if value == "" {
		return nil
	}
	return &value
}

func optionalInt(hasValue bool, value int64) *int {
	if !hasValue {
		return nil
	}
	converted := int(value)
	return &converted
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
