apiVersion: v1
kind: Service
metadata:
  name: {{ include "ponctuel.fullname" . }}-api
  labels:
    {{- include "ponctuel.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    {{- include "ponctuel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
